# Generated by Django 4.0.2 on 2022-04-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.userchat'),
        ),
        migrations.AddField(
            model_name='userchat',
            name='users',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessagetranslation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chats.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='chats.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_channel_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communities.channel'),
        ),
        migrations.AddConstraint(
            model_name='userchatmessagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'message'), name='user_unique_language_message'),
        ),
        migrations.AddConstraint(
            model_name='channelchatmessagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'message'), name='channel_unique_language_message'),
        ),
    ]
