# Generated by Django 4.0.2 on 2022-03-10 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_initial'),
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessagetranslation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chats.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='chats.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_channel_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channel'),
        ),
        migrations.AddConstraint(
            model_name='userchatmessagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'message'), name='user_unique_language_message'),
        ),
        migrations.AddConstraint(
            model_name='userchatmessage',
            constraint=models.CheckConstraint(check=models.Q(('recipient', django.db.models.expressions.F('author')), _negated=True), name='author_not_equals_recipient'),
        ),
        migrations.AddConstraint(
            model_name='channelchatmessagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'message'), name='channel_unique_language_message'),
        ),
    ]
