# Generated by Django 4.0.2 on 2022-05-27 10:50

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelchatmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=chats.models.upload_to_channel_chat_message),
        ),
        migrations.AddField(
            model_name='friendchatmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=chats.models.upload_to_friend_chat_message),
        ),
    ]
