# Generated by Django 4.0.2 on 2022-04-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_alter_friendchat_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
