version: "3.9"

services:
  db:
    image: postgres:14
    expose:
      - "5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6
    expose:
      - "6379"
    volumes:
      - redis-volume:/data

  api:
    build:
      context: .
      dockerfile: DockerfileProd
    command: sh -c "/wait && cd /code && daphne -b 0.0.0.0 tandem.asgi:application"
    expose:
      - "8000"
    environment:
      - WAIT_HOSTS=db:5432, redis:6379
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - media-volume:/files

  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - api

volumes:
  db-volume:
  redis-volume:
  media-volume:

networks:
  default:
      name: tandem-network
      external: true

# Source: https://docs.docker.com/samples/django/