# Generated by Django 4.0.2 on 2022-04-27 15:52

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, upload_to=communities.models.upload_to),
        ),
    ]
