# Generated by Django 4.0.2 on 2022-02-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelinterest',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='channels.channel'),
        ),
        migrations.AddField(
            model_name='channelchatmessagetranslation',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='channels.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessagecorrection',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='channels.channelchatmessage'),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_channel_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channel'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(check=models.Q(('end_proficiency_level__gte', django.db.models.expressions.F('start_proficiency_level'))), name='start_proficiency_level_gte_end_proficiency_level'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='unique_user_channel'),
        ),
        migrations.AddConstraint(
            model_name='channelinterest',
            constraint=models.UniqueConstraint(fields=('channel', 'interest'), name='unique_channel_interest'),
        ),
        migrations.AddConstraint(
            model_name='channelchatmessagetranslation',
            constraint=models.UniqueConstraint(fields=('language', 'message'), name='channel_unique_language_message'),
        ),
    ]
